services:
  db:
    image: postgres:17
    container_name: postgres-dev
    environment:
      POSTGRES_DB: ceres_temp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '@Test1234'
    ports:
      - "5434:5432"   # Host 5434 -> Container 5432
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-dev
    ports:
      - "6379:6379"   # Host 6379 -> Container 6379
    volumes:
        - redis-data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ceres-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ceres_temp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: '@Test1234'
      gcpBucketName: ceres-bucket
      gcpProjectId: banded-plateau-321516
      gcpCredentialsFile: classpath:banded-plateau-321516-006939d9d275.json
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "7107:8080"   # Host 7107 -> Container 8080
    depends_on:
      - db
      - redis

volumes:
  db-data:
  redis-data:
