services:
  db:
    image: postgres:17
    container_name: blip-db
    environment:
      POSTGRES_DB: blip
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '@Test1234'
    ports:
      - "5434:5432"   # Host 5434 -> Container 5432
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: blip-redis
    ports:
      - "6379:6379"   # Host 6379 -> Container 6379
    volumes:
        - redis-data:/data

  zipkin:
    image: openzipkin/zipkin:2.23.0
    container_name: blip-zipkin
    ports:
      - "9411:9411"  # Host 9411 -> Container 9411

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blip-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blip
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: '@Test1234'
      gcpBucketName: ceres-bucket
      gcpProjectId: hooker-b3f8d
      gcpCredentialsFile: classpath:hooker-b3f8d-firebase-adminsdk-2y0f3-2097b8a4dd.json
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "7107:8080"   # Host 7107 -> Container 8080
    depends_on:
      - db
      - redis
      - zipkin

volumes:
  db-data:
  redis-data:
