# database settings
spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true

    hibernate:
      ddl-auto: none

    show-sql: false

  liquibase:
    change-log: classpath:liquibase/db.changelog.xml

  mail:
    default-encoding: UTF-8
    properties:
      protocol: smtp
      test-connection: false
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    host: smtp.gmail.com
    port: 587

    username: ${smtpUsername}
    password: ${smtpPassword}

  profiles:
    active: dev

  cloud:
    gcp:
      credentials:
        location: ${gcpCredentialsFile}
      config:
        project-id: ${gcpProjectId}
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  servlet:
    multipart:
      location: blip-files

secret: 25432A462D4A614E645267556B586E3272357538782F413F4428472B4B6250655368566D5971337336763979244226452948404D635166546A576E5A72347537

app:
  name: ceres-projects
  version: VER20240713001

file.upload-dir: ceres_files


USE_DOMAINS: true

logging:
  level:
    web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator

  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0
server:
  jetty:
    connection-idle-timeout: 150000 # 150 seconds

gcp:
  bucket:
    name: ${gcpBucketName}

application:
  url: https://blip.sakisofts.com

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /api-docs